# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from scale_truck_control_msgs/lrc2ocr.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class lrc2ocr(genpy.Message):
  _md5sum = "4df4cc808fb5dda1620117e19736ec90"
  _type = "scale_truck_control_msgs/lrc2ocr"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 index
float32 steer_angle
float32 cur_dist
float32 tar_dist
float32 tar_vel
float32 pred_vel
bool alpha
"""
  __slots__ = ['index','steer_angle','cur_dist','tar_dist','tar_vel','pred_vel','alpha']
  _slot_types = ['int32','float32','float32','float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       index,steer_angle,cur_dist,tar_dist,tar_vel,pred_vel,alpha

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(lrc2ocr, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.index is None:
        self.index = 0
      if self.steer_angle is None:
        self.steer_angle = 0.
      if self.cur_dist is None:
        self.cur_dist = 0.
      if self.tar_dist is None:
        self.tar_dist = 0.
      if self.tar_vel is None:
        self.tar_vel = 0.
      if self.pred_vel is None:
        self.pred_vel = 0.
      if self.alpha is None:
        self.alpha = False
    else:
      self.index = 0
      self.steer_angle = 0.
      self.cur_dist = 0.
      self.tar_dist = 0.
      self.tar_vel = 0.
      self.pred_vel = 0.
      self.alpha = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i5fB().pack(_x.index, _x.steer_angle, _x.cur_dist, _x.tar_dist, _x.tar_vel, _x.pred_vel, _x.alpha))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.index, _x.steer_angle, _x.cur_dist, _x.tar_dist, _x.tar_vel, _x.pred_vel, _x.alpha,) = _get_struct_i5fB().unpack(str[start:end])
      self.alpha = bool(self.alpha)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i5fB().pack(_x.index, _x.steer_angle, _x.cur_dist, _x.tar_dist, _x.tar_vel, _x.pred_vel, _x.alpha))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.index, _x.steer_angle, _x.cur_dist, _x.tar_dist, _x.tar_vel, _x.pred_vel, _x.alpha,) = _get_struct_i5fB().unpack(str[start:end])
      self.alpha = bool(self.alpha)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i5fB = None
def _get_struct_i5fB():
    global _struct_i5fB
    if _struct_i5fB is None:
        _struct_i5fB = struct.Struct("<i5fB")
    return _struct_i5fB
