// Generated by gencpp from file scale_truck_control/lane.msg
// DO NOT EDIT!


#ifndef SCALE_TRUCK_CONTROL_MESSAGE_LANE_H
#define SCALE_TRUCK_CONTROL_MESSAGE_LANE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scale_truck_control
{
template <class ContainerAllocator>
struct lane_
{
  typedef lane_<ContainerAllocator> Type;

  lane_()
    : a(0.0)
    , b(0.0)
    , c(0.0)  {
    }
  lane_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)
    , c(0.0)  {
  (void)_alloc;
    }



   typedef float _a_type;
  _a_type a;

   typedef float _b_type;
  _b_type b;

   typedef float _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::scale_truck_control::lane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scale_truck_control::lane_<ContainerAllocator> const> ConstPtr;

}; // struct lane_

typedef ::scale_truck_control::lane_<std::allocator<void> > lane;

typedef boost::shared_ptr< ::scale_truck_control::lane > lanePtr;
typedef boost::shared_ptr< ::scale_truck_control::lane const> laneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scale_truck_control::lane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scale_truck_control::lane_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scale_truck_control::lane_<ContainerAllocator1> & lhs, const ::scale_truck_control::lane_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scale_truck_control::lane_<ContainerAllocator1> & lhs, const ::scale_truck_control::lane_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scale_truck_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scale_truck_control::lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scale_truck_control::lane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scale_truck_control::lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scale_truck_control::lane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scale_truck_control::lane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scale_truck_control::lane_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scale_truck_control::lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d20f63a7e99cd5689c2dcf93cf2f8085";
  }

  static const char* value(const ::scale_truck_control::lane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd20f63a7e99cd568ULL;
  static const uint64_t static_value2 = 0x9c2dcf93cf2f8085ULL;
};

template<class ContainerAllocator>
struct DataType< ::scale_truck_control::lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scale_truck_control/lane";
  }

  static const char* value(const ::scale_truck_control::lane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scale_truck_control::lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a\n"
"float32 b\n"
"float32 c\n"
;
  }

  static const char* value(const ::scale_truck_control::lane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scale_truck_control::lane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scale_truck_control::lane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scale_truck_control::lane_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<float>::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCALE_TRUCK_CONTROL_MESSAGE_LANE_H
