// Generated by gencpp from file scale_truck_control_msgs/lane.msg
// DO NOT EDIT!


#ifndef SCALE_TRUCK_CONTROL_MSGS_MESSAGE_LANE_H
#define SCALE_TRUCK_CONTROL_MSGS_MESSAGE_LANE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scale_truck_control_msgs
{
template <class ContainerAllocator>
struct lane_
{
  typedef lane_<ContainerAllocator> Type;

  lane_()
    : c0(0.0)
    , c1(0.0)
    , c2(0.0)  {
    }
  lane_(const ContainerAllocator& _alloc)
    : c0(0.0)
    , c1(0.0)
    , c2(0.0)  {
  (void)_alloc;
    }



   typedef float _c0_type;
  _c0_type c0;

   typedef float _c1_type;
  _c1_type c1;

   typedef float _c2_type;
  _c2_type c2;





  typedef boost::shared_ptr< ::scale_truck_control_msgs::lane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scale_truck_control_msgs::lane_<ContainerAllocator> const> ConstPtr;

}; // struct lane_

typedef ::scale_truck_control_msgs::lane_<std::allocator<void> > lane;

typedef boost::shared_ptr< ::scale_truck_control_msgs::lane > lanePtr;
typedef boost::shared_ptr< ::scale_truck_control_msgs::lane const> laneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scale_truck_control_msgs::lane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scale_truck_control_msgs::lane_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scale_truck_control_msgs::lane_<ContainerAllocator1> & lhs, const ::scale_truck_control_msgs::lane_<ContainerAllocator2> & rhs)
{
  return lhs.c0 == rhs.c0 &&
    lhs.c1 == rhs.c1 &&
    lhs.c2 == rhs.c2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scale_truck_control_msgs::lane_<ContainerAllocator1> & lhs, const ::scale_truck_control_msgs::lane_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scale_truck_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scale_truck_control_msgs::lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scale_truck_control_msgs::lane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scale_truck_control_msgs::lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scale_truck_control_msgs::lane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scale_truck_control_msgs::lane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scale_truck_control_msgs::lane_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scale_truck_control_msgs::lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb37e2a7d1c9ea86f0485c19147d8e3a";
  }

  static const char* value(const ::scale_truck_control_msgs::lane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb37e2a7d1c9ea86ULL;
  static const uint64_t static_value2 = 0xf0485c19147d8e3aULL;
};

template<class ContainerAllocator>
struct DataType< ::scale_truck_control_msgs::lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scale_truck_control_msgs/lane";
  }

  static const char* value(const ::scale_truck_control_msgs::lane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scale_truck_control_msgs::lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 c0  # a\n"
"float32 c1  # b\n"
"float32 c2  # c\n"
;
  }

  static const char* value(const ::scale_truck_control_msgs::lane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scale_truck_control_msgs::lane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.c0);
      stream.next(m.c1);
      stream.next(m.c2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scale_truck_control_msgs::lane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scale_truck_control_msgs::lane_<ContainerAllocator>& v)
  {
    s << indent << "c0: ";
    Printer<float>::stream(s, indent + "  ", v.c0);
    s << indent << "c1: ";
    Printer<float>::stream(s, indent + "  ", v.c1);
    s << indent << "c2: ";
    Printer<float>::stream(s, indent + "  ", v.c2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCALE_TRUCK_CONTROL_MSGS_MESSAGE_LANE_H
