// Generated by gencpp from file scale_truck_control_msgs/ocr2lrc.msg
// DO NOT EDIT!


#ifndef SCALE_TRUCK_CONTROL_MSGS_MESSAGE_OCR2LRC_H
#define SCALE_TRUCK_CONTROL_MSGS_MESSAGE_OCR2LRC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scale_truck_control_msgs
{
template <class ContainerAllocator>
struct ocr2lrc_
{
  typedef ocr2lrc_<ContainerAllocator> Type;

  ocr2lrc_()
    : cur_vel(0.0)
    , u_k(0.0)  {
    }
  ocr2lrc_(const ContainerAllocator& _alloc)
    : cur_vel(0.0)
    , u_k(0.0)  {
  (void)_alloc;
    }



   typedef float _cur_vel_type;
  _cur_vel_type cur_vel;

   typedef float _u_k_type;
  _u_k_type u_k;





  typedef boost::shared_ptr< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> const> ConstPtr;

}; // struct ocr2lrc_

typedef ::scale_truck_control_msgs::ocr2lrc_<std::allocator<void> > ocr2lrc;

typedef boost::shared_ptr< ::scale_truck_control_msgs::ocr2lrc > ocr2lrcPtr;
typedef boost::shared_ptr< ::scale_truck_control_msgs::ocr2lrc const> ocr2lrcConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator1> & lhs, const ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator2> & rhs)
{
  return lhs.cur_vel == rhs.cur_vel &&
    lhs.u_k == rhs.u_k;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator1> & lhs, const ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scale_truck_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5547173125610f649bee41045fabb0de";
  }

  static const char* value(const ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5547173125610f64ULL;
  static const uint64_t static_value2 = 0x9bee41045fabb0deULL;
};

template<class ContainerAllocator>
struct DataType< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scale_truck_control_msgs/ocr2lrc";
  }

  static const char* value(const ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 cur_vel\n"
"float32 u_k\n"
;
  }

  static const char* value(const ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cur_vel);
      stream.next(m.u_k);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ocr2lrc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scale_truck_control_msgs::ocr2lrc_<ContainerAllocator>& v)
  {
    s << indent << "cur_vel: ";
    Printer<float>::stream(s, indent + "  ", v.cur_vel);
    s << indent << "u_k: ";
    Printer<float>::stream(s, indent + "  ", v.u_k);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCALE_TRUCK_CONTROL_MSGS_MESSAGE_OCR2LRC_H
